apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: three-tier-app-database:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_USER
              value: dbuser
            - name: POSTGRES_PASSWORD
              value: password123
          ports:
            - containerPort: 5432